/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package peaches.proyectoalejo.update;

import peaches.proyectoalejo.model.Vehiculo;
import peaches.proyectoalejo.service.VehiculoService;
import peaches.proyectoalejo.util.DialogBuscarCliente;
import peaches.proyectoalejo.util.DialogBuscarClienteUpdate;
import peaches.proyectoalejo.util.Oyente;

/**
 *
 * @author Lucero
 */
public class upVehiculo extends javax.swing.JFrame {
    private Oyente vehiculoOyente;
    String placa;
    
    VehiculoService vehiculoService=new VehiculoService();
    /**
     * 
     * Creates new form upVehiculo
     */
    public upVehiculo() {
        initComponents();
    }
     public upVehiculo(String placa, Oyente click) {
        this.placa = placa;
        this.vehiculoOyente = click;
        System.out.println("observacion");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtClientes = new javax.swing.JTextField();
        btnCliente = new javax.swing.JButton();
        btnRegistrarVehiculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("NUEVO MODELO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel3.setText("NUEVO CLIENTE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        txtModelo.setBackground(new java.awt.Color(202, 202, 202));
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 140, -1));

        txtClientes.setText("jTextField1");
        jPanel1.add(txtClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        btnCliente.setText("Seleccionar Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 120, -1));

        btnRegistrarVehiculo.setBackground(new java.awt.Color(255, 51, 51));
        btnRegistrarVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarVehiculo.setText("REGISTRAR");
        btnRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        DialogBuscarClienteUpdate cliente= new DialogBuscarClienteUpdate(this,true);
        cliente.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVehiculoActionPerformed
       String nuevoModelo = txtModelo.getText();
       String nuevoCliente = txtClientes.getText();
      
       
       
      Vehiculo  vehiculoActualizado = new Vehiculo();
      vehiculoActualizado.setPlaca(placa);
       vehiculoActualizado.setModelo(nuevoModelo);
       vehiculoActualizado.setDni(nuevoCliente);
     
       
       vehiculoService.actualizarVehiculo(vehiculoActualizado);
        vehiculoOyente.anadido();
         
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarVehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(upVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(upVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(upVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(upVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new upVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnRegistrarVehiculo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtClientes;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
