/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package peaches.proyectoalejo.dialog;

import java.awt.Frame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import peaches.proyectoalejo.agregar.popVehiculo;
import peaches.proyectoalejo.model.Repuesto;
import peaches.proyectoalejo.service.RepuestoService;
import peaches.proyectoalejo.util.Conexion;
import peaches.proyectoalejo.view.framePrincipal;
import peaches.proyectoalejo.view.panelVenta;

/**
 *
 * @author Lucero
 */
public class DialogBuscarRepuesto extends javax.swing.JDialog {
    
    RepuestoService repuestoService = new RepuestoService();

    /**
     * Creates new form DialogBuscarRepuesto
     */
    public DialogBuscarRepuesto(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
        initComponents();
        
        mostrarRepuestos();
    }
    
    
    
     public void mostrarRepuestos() {
        List<Repuesto> ListaDeRepuestos = repuestoService.obtenerTodosLosRepuestos();
        DefaultTableModel model = (DefaultTableModel) visorRepuestos.getModel();
        model.setRowCount(0); // Limpiar la tabla antes de agregar nuevos datos

        for (Repuesto re : ListaDeRepuestos) {
            model.addRow(new Object[]{re.getIdRepuesto(), re.getDescripcion(), re.getStock(), re.getPrecio()});
        }
    }
     
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visorRepuestos = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visorRepuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Descripcion", "Stock", "Precio"
            }
        ));
        jScrollPane1.setViewportView(visorRepuestos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 87, 350, 108));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 90, -1));

        jLabel1.setText("Buscar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 50, -1, -1));

        jButton1.setText("Selecionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 232, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

 if(visorRepuestos.getSelectedRow()>=0){
             if (visorRepuestos.getSelectedRow() >= 0) {
        try {
            DefaultTableModel tm = (DefaultTableModel) visorRepuestos.getModel();
            String id = String.valueOf(tm.getValueAt(visorRepuestos.getSelectedRow(), 0));
            String descripcion = String.valueOf(tm.getValueAt(visorRepuestos.getSelectedRow(), 1));
           int stock = Integer.parseInt(String.valueOf(tm.getValueAt(visorRepuestos.getSelectedRow(), 2)));

            double precio = Double.parseDouble(String.valueOf(tm.getValueAt(visorRepuestos.getSelectedRow(), 3)));
            
            // Agregar el repuesto al panel de ventas
        //    framePrincipal.panelVentas.agregarRepuesto(id, descripcion,stock, precio);
        
        framePrincipal fp = new framePrincipal();
        fp.getPanelVenta().agregarRepuesto(id, descripcion, stock, precio);
        
   
            dispose(); // Cerrar el diálogo
        } catch (Exception e) {
            e.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Error", "SISTEMA", JOptionPane.WARNING_MESSAGE);
             }
             }   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogBuscarRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogBuscarRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogBuscarRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogBuscarRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogBuscarRepuesto dialog = new DialogBuscarRepuesto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable visorRepuestos;
    // End of variables declaration//GEN-END:variables
}
