/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package peaches.proyectoalejo.dialog;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import peaches.proyectoalejo.model.DetalleRepuesto;
import peaches.proyectoalejo.model.DetalleServicio;
import peaches.proyectoalejo.model.Empleado;
import peaches.proyectoalejo.model.Repuesto;
import peaches.proyectoalejo.model.Servicio;
import peaches.proyectoalejo.model.Venta;
import peaches.proyectoalejo.service.DetalleRepuestoService;
import peaches.proyectoalejo.service.DetalleServicioService;
import peaches.proyectoalejo.service.EmpleadoService;
import peaches.proyectoalejo.service.RepuestoService;
import peaches.proyectoalejo.service.ServicioService;
import peaches.proyectoalejo.service.VentaService;

/**
 *
 * @author santo
 */
public class DialogMostrarDetalleVenta extends javax.swing.JDialog {
    String idVenta;
    double totalServicio, totalRepuesto;
    VentaService ventaService = new VentaService();
    DetalleServicioService detalleServicioService = new DetalleServicioService();
        DetalleRepuestoService detalleRepuestoService = new DetalleRepuestoService();
        RepuestoService repuestoService = new RepuestoService();
        EmpleadoService empleadoService = new EmpleadoService();

ServicioService servicioService = new ServicioService();

    /**
     * Creates new form DialogMostrarDetalleVenta
     */
    public DialogMostrarDetalleVenta(java.awt.Frame parent, boolean modal, String idVenta) {
        super(parent, modal);
        initComponents();
        this.idVenta = idVenta;

        mostrarInfo();
         }
    
   void mostrarInfo(){
       
           Venta venta = ventaService.obtenerVentaPorId(idVenta);
           lblTotal.setText(venta.getFecha().toString());
            List<DetalleServicio> ListaDetalleServicio = detalleServicioService.obtenerTodosDetalleServicioPorVenta(idVenta);
            List<DetalleRepuesto> ListaDetalleRepuesto = detalleRepuestoService.obtenerTodosDetalleRepuestosPorVenta(idVenta);
            
            Empleado empleado = empleadoService.obtenerEmpleadoDni(venta.getDniEmpleado());

         double total = 0.0;

        StringBuilder detallesServicioStr = new StringBuilder();
              StringBuilder detallesRepuestoStr = new StringBuilder();

  
        
        for (DetalleServicio detalleServicio : ListaDetalleServicio)
        {
              
                Servicio servicio = servicioService.obtenerServicioPorId(detalleServicio.getIdServicio());
   
        
                 totalServicio += detalleServicio.getPrecio();
      
      
                detallesServicioStr.append(servicio.getDescripcion());
                detallesServicioStr.append(", Precio: ");
                detallesServicioStr.append(String.valueOf(servicio.getPrecio()));
                detallesServicioStr.append("\n");
        
                 }
        
      for (DetalleRepuesto detalleRepuesto : ListaDetalleRepuesto)
      {
          
            Repuesto repuesto = repuestoService.obtenerRepuestoPorId(detalleRepuesto.getIdRepuesto());
            
            totalRepuesto += detalleRepuesto.getTotal();
                  
        detallesRepuestoStr.append(repuesto.getDescripcion());
        detallesRepuestoStr.append(", Precio: ");
        detallesRepuestoStr.append(String.valueOf(repuesto.getPrecio()));
         detallesRepuestoStr.append(", Cantidad: ");
        detallesRepuestoStr.append(String.valueOf(detalleRepuesto.getCantidad()));
                 detallesRepuestoStr.append(", ");

               detallesRepuestoStr.append(String.valueOf(detalleRepuesto.getPrecioUnidad()));
                 detallesRepuestoStr.append(", ");

              detallesRepuestoStr.append(String.valueOf(detalleRepuesto.getTotal()));

        detallesRepuestoStr.append("\n");
             }
        
      total = totalRepuesto+totalServicio;
           // tableServicios.setModel(model);
       lblDniEmpleado.setText(empleado.getNombreEmpleado());

        lblEmpleado.setText(venta.getDniEmpleado());
        
        lblTotal.setText(String.valueOf(total));
       txtRepoServicios.setText(detallesServicioStr.toString());
       txtRepoRepuestos.setText(detallesRepuestoStr.toString());
       
             
    }       


    private DialogMostrarDetalleVenta(JFrame jFrame, boolean b) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRepoServicios = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        lblTotalServicios = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRepoRepuestos = new javax.swing.JTextArea();
        lblTotalRepuestos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDniEmpleado = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("SISTEMA CYR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 330, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("REPUESTOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 300, -1));

        lblTotal.setText("...");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 190, 20));

        jScrollPane1.setBorder(null);

        txtRepoServicios.setBackground(new java.awt.Color(255, 255, 255));
        txtRepoServicios.setColumns(20);
        txtRepoServicios.setRows(5);
        jScrollPane1.setViewportView(txtRepoServicios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 310, 80));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Av. Túpac Amaru Nº 7140 MZ. L-02 Lote Nº 13 P.J. Año Nuevo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 350, 20));
        jPanel1.add(lblTotalServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 80, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("SERVICIOS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 270, 20));

        jScrollPane2.setBorder(null);

        txtRepoRepuestos.setBackground(new java.awt.Color(255, 255, 255));
        txtRepoRepuestos.setColumns(20);
        txtRepoRepuestos.setRows(5);
        txtRepoRepuestos.setBorder(null);
        jScrollPane2.setViewportView(txtRepoRepuestos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 310, 80));
        jPanel1.add(lblTotalRepuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 50, 20));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Total");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 80, -1));

        lblDniEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        lblDniEmpleado.setText(".");
        jPanel1.add(lblDniEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 210, 20));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Atendido Por:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 90, 20));

        lblEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        lblEmpleado.setText(".");
        jPanel1.add(lblEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 210, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogMostrarDetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogMostrarDetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogMostrarDetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogMostrarDetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogMostrarDetalleVenta dialog = new DialogMostrarDetalleVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDniEmpleado;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalRepuestos;
    private javax.swing.JLabel lblTotalServicios;
    private javax.swing.JTextArea txtRepoRepuestos;
    private javax.swing.JTextArea txtRepoServicios;
    // End of variables declaration//GEN-END:variables
}
