/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package peaches.proyectoalejo.dialog;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import peaches.proyectoalejo.model.DetalleRepuesto;
import peaches.proyectoalejo.model.DetalleServicio;
import peaches.proyectoalejo.model.Servicio;
import peaches.proyectoalejo.service.DetalleServicioService;
import peaches.proyectoalejo.service.ServicioService;
import peaches.proyectoalejo.util.Conexion;
import peaches.proyectoalejo.util.Oyente;

/**
 *
 * @author Lucero
 */
public class DialogBuscarServicio extends javax.swing.JDialog {
    DetalleServicioService detalleServicioService = new DetalleServicioService();
    Oyente click;
    ServicioService servicioService = new ServicioService();
    String idVenta;

    /**
     * Creates new form DialogBuscarServicio
     */
    public DialogBuscarServicio(java.awt.Frame parent, boolean modal, String idVenta, Oyente click) {
        super(parent, modal);
        initComponents();
        mostrarServicios();
        this.idVenta = idVenta;
        this.click = click;
    }

    private DialogBuscarServicio(JFrame jFrame, boolean b) {
    }
    
  public void mostrarServicios() {
        List<Servicio> servicios = servicioService.obtenerTodosLosServicios();
        DefaultTableModel model = (DefaultTableModel) visorServicios.getModel();
        model.setRowCount(0); // Limpiar la tabla antes de agregar nuevos datos

        for (Servicio servicio : servicios) {
            model.addRow(new Object[]{servicio.getIdServicio(), servicio.getDescripcion(), servicio.getPrecio()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        visorServicios = new javax.swing.JTable();
        btnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 42, -1, -1));

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 39, 71, -1));

        visorServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Descripcion", "Precio"
            }
        ));
        jScrollPane1.setViewportView(visorServicios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 87, 329, 131));

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 277, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed

         if(visorServicios.getSelectedRow()>=0){
             if (visorServicios.getSelectedRow() >= 0) {
        try {
            DefaultTableModel tm = (DefaultTableModel) visorServicios.getModel();
            int idServicio = Integer.parseInt(String.valueOf(tm.getValueAt(visorServicios.getSelectedRow(), 0)));
            double precio = Double.parseDouble(String.valueOf(tm.getValueAt(visorServicios.getSelectedRow(), 2)));
            
            DetalleServicio detalle = new DetalleServicio();
            detalle.setIdVenta(idVenta);
            detalle.setIdServicio(idServicio);
            detalle.setPrecio(precio);
      
            
            detalleServicioService.guardarDetalleServicio(detalle);
            click.anadido();
            dispose(); // Cerrar el diálogo
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Error", "SISTEMA", JOptionPane.WARNING_MESSAGE);
             }
             
             }  

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogBuscarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogBuscarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogBuscarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogBuscarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogBuscarServicio dialog = new DialogBuscarServicio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable visorServicios;
    // End of variables declaration//GEN-END:variables
}
