/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package peaches.pelioficial.view;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import peaches.pelioficial.util.ImageUtils;

/**
 *
 * @author santo
 */
public class panelCartelera extends javax.swing.JPanel {
    
    private framePrincipal framePrincipal;
    
    /**
     * Creates new form panelCartelera
     */
    public panelCartelera(framePrincipal framePrincipal) {
        initComponents();
        this.framePrincipal = framePrincipal;
        pSinopsis.setVisible(false);
    }
    
    public void verCaracteristica(){
        this.setLayout(new BorderLayout());
        framePrincipal.mostrarPanelMenu();
        this.revalidate();
        this.repaint(); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pSinopsis = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/FNAF.jpg"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton1ComponentResized(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 90, 130));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/ExtranioMundoDeJack.jpg"))); // NOI18N
        jButton2.setText("jButton1");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton2ComponentResized(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 90, 130));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/ElHobbit.jpg"))); // NOI18N
        jButton3.setText("jButton1");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton3ComponentResized(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 90, 130));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/DragonBall.jpg"))); // NOI18N
        jButton4.setText("jButton1");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton4ComponentResized(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 90, 130));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/Batman.jpg"))); // NOI18N
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton5ComponentResized(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 260));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/DestinoFinal.jpg"))); // NOI18N
        jButton6.setText("jButton1");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton6ComponentResized(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 90, 130));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/BusquedaImplacable.jpg"))); // NOI18N
        jButton7.setText("jButton1");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton7ComponentResized(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 90, 130));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/Pixeles.jpg"))); // NOI18N
        jButton8.setText("jButton1");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton8ComponentResized(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 90, 120));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/Matrix.jpg"))); // NOI18N
        jButton9.setText("jButton1");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton9ComponentResized(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 90, 120));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/MarioBros.jpg"))); // NOI18N
        jButton10.setText("jButton1");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton10ComponentResized(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 90, 120));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/JurassicWorld.jpg"))); // NOI18N
        jButton11.setText("jButton1");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton11ComponentResized(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 90, 120));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/Ju-On.jpg"))); // NOI18N
        jButton12.setText("jButton1");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton12ComponentResized(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 90, 120));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/Intensamente.jpg"))); // NOI18N
        jButton13.setText("jButton1");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton13ComponentResized(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 90, 120));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/Susy.jpg"))); // NOI18N
        jButton15.setText("jButton1");
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton15ComponentResized(evt);
            }
        });
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 90, 120));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/Soul.jpg"))); // NOI18N
        jButton16.setText("jButton1");
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton16ComponentResized(evt);
            }
        });
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 90, 120));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/ScaryMovie.jpg"))); // NOI18N
        jButton17.setText("jButton1");
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton17ComponentResized(evt);
            }
        });
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 90, 120));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/RapidosFuriososX.jpg"))); // NOI18N
        jButton18.setText("jButton1");
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton18ComponentResized(evt);
            }
        });
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 90, 120));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/Quantumania.jpg"))); // NOI18N
        jButton19.setText("jButton1");
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton19ComponentResized(evt);
            }
        });
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 90, 120));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/Vengadores.jpg"))); // NOI18N
        jButton20.setText("jButton1");
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton20.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton20ComponentResized(evt);
            }
        });
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 90, 120));

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/Ted.jpg"))); // NOI18N
        jButton21.setText("jButton1");
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jButton21ComponentResized(evt);
            }
        });
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 90, 120));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Cartelera");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 30));

        pSinopsis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Imgs Cartelera/Pixeles.jpg"))); // NOI18N
        pSinopsis.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 250));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel16.setText("PIXELES");
        pSinopsis.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jLabel17.setText("<html>\nSINOPSIS: <br>\nEn 1982, la NASA envió una sonda el espacio con la esperanza de contactar<br>\n con otras  formas de vida extraterrestre. <br>\nElla incluía muestras de nuestra cultura, como videojuegos  recreativos de los años <br>\nochenta.<br>\n</html>");
        pSinopsis.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 460, 90));

        jLabel18.setText("ESTADO:");
        pSinopsis.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jLabel19.setText("disponible");
        pSinopsis.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        jLabel20.setText("DIRECTOR:");
        pSinopsis.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, 10));

        jLabel21.setText("Chris Columbus");
        pSinopsis.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jLabel22.setText("´GÉNERO:");
        pSinopsis.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jLabel23.setText("Animación y fantasía");
        pSinopsis.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pSinopsis.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 490, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        verCaracteristica();
      
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        verCaracteristica();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        verCaracteristica();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        verCaracteristica();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
verCaracteristica();        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   verCaracteristica();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
verCaracteristica();    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
verCaracteristica();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
verCaracteristica();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
verCaracteristica();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
verCaracteristica();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
verCaracteristica();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
verCaracteristica();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
verCaracteristica();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
verCaracteristica();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
verCaracteristica();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
verCaracteristica();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
verCaracteristica();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
verCaracteristica();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        verCaracteristica();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton5ComponentResized
        ImageUtils.escalarImagen(jButton5, "/Imgs/Imgs Cartelera/Batman.jpg");
    }//GEN-LAST:event_jButton5ComponentResized

    private void jButton7ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton7ComponentResized
        ImageUtils.escalarImagen(jButton7, "/Imgs/Imgs Cartelera/BusquedaImplacable.jpg");
    }//GEN-LAST:event_jButton7ComponentResized

    private void jButton6ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton6ComponentResized
        ImageUtils.escalarImagen(jButton6, "/Imgs/Imgs Cartelera/DestinoFinal.jpg");
    }//GEN-LAST:event_jButton6ComponentResized

    private void jButton4ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton4ComponentResized
        ImageUtils.escalarImagen(jButton4, "/Imgs/Imgs Cartelera/DragonBall.jpg");
    }//GEN-LAST:event_jButton4ComponentResized

    private void jButton3ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton3ComponentResized
        ImageUtils.escalarImagen(jButton3, "/Imgs/Imgs Cartelera/ElHobbit.jpg");
    }//GEN-LAST:event_jButton3ComponentResized

    private void jButton2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton2ComponentResized
        ImageUtils.escalarImagen(jButton2, "/Imgs/Imgs Cartelera/ExtranioMundoDeJack.jpg");
    }//GEN-LAST:event_jButton2ComponentResized

    private void jButton1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton1ComponentResized
        ImageUtils.escalarImagen(jButton1, "/Imgs/Imgs Cartelera/FNAF.jpg");
    }//GEN-LAST:event_jButton1ComponentResized

    private void jButton13ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton13ComponentResized
        ImageUtils.escalarImagen(jButton13, "/Imgs/Imgs Cartelera/Intensamente.jpg");
    }//GEN-LAST:event_jButton13ComponentResized

    private void jButton12ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton12ComponentResized
        ImageUtils.escalarImagen(jButton12, "/Imgs/Imgs Cartelera/Ju-On.jpg");
    }//GEN-LAST:event_jButton12ComponentResized

    private void jButton11ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton11ComponentResized
        ImageUtils.escalarImagen(jButton11, "/Imgs/Imgs Cartelera/JurassicWorld.jpg");
    }//GEN-LAST:event_jButton11ComponentResized

    private void jButton10ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton10ComponentResized
        ImageUtils.escalarImagen(jButton10, "/Imgs/Imgs Cartelera/MarioBros.jpg");
    }//GEN-LAST:event_jButton10ComponentResized

    private void jButton9ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton9ComponentResized
        ImageUtils.escalarImagen(jButton9, "/Imgs/Imgs Cartelera/Matrix.jpg");
    }//GEN-LAST:event_jButton9ComponentResized

    private void jButton8ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton8ComponentResized
        ImageUtils.escalarImagen(jButton8, "/Imgs/Imgs Cartelera/Pixeles.jpg");
    }//GEN-LAST:event_jButton8ComponentResized

    private void jButton19ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton19ComponentResized
        ImageUtils.escalarImagen(jButton19, "/Imgs/Imgs Cartelera/Quantumania.jpg");
    }//GEN-LAST:event_jButton19ComponentResized

    private void jButton18ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton18ComponentResized
        ImageUtils.escalarImagen(jButton18, "/Imgs/Imgs Cartelera/RapidosFuriososX.jpg");
    }//GEN-LAST:event_jButton18ComponentResized

    private void jButton17ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton17ComponentResized
        ImageUtils.escalarImagen(jButton17, "/Imgs/Imgs Cartelera/ScaryMovie.jpg");
    }//GEN-LAST:event_jButton17ComponentResized

    private void jButton16ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton16ComponentResized
        ImageUtils.escalarImagen(jButton16, "/Imgs/Imgs Cartelera/Soul.jpg");
    }//GEN-LAST:event_jButton16ComponentResized

    private void jButton15ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton15ComponentResized
        ImageUtils.escalarImagen(jButton15, "/Imgs/Imgs Cartelera/Susy.jpg");
    }//GEN-LAST:event_jButton15ComponentResized

    private void jButton21ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton21ComponentResized
        ImageUtils.escalarImagen(jButton21, "/Imgs/Imgs Cartelera/Ted.jpg");
    }//GEN-LAST:event_jButton21ComponentResized

    private void jButton20ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButton20ComponentResized
        ImageUtils.escalarImagen(jButton20, "/Imgs/Imgs Cartelera/Vengadores.jpg");
    }//GEN-LAST:event_jButton20ComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pSinopsis;
    // End of variables declaration//GEN-END:variables
}
