/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package peaches.proyectoalejo.view;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import peaches.proyectoalejo.dialog.DialogBuscarRepuesto;
import peaches.proyectoalejo.dialog.DialogBuscarServicio;

/**
 *
 * @author santo
 */
public class panelVenta extends javax.swing.JPanel {

    /**
     * Creates new form panelVenta
     */
    public panelVenta() {
        initComponents();
    }
    
   public void agregarRepuesto(String id, String descripcion, int stock, double precio) {
    // Agregar lógica para agregar repuesto a la tabla
    
    DefaultTableModel model = (DefaultTableModel) tableRepuestos.getModel();
    model.addRow(new Object[]{id, descripcion, stock, precio});
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSeleccionarServicio = new javax.swing.JButton();
        btnSeleccionarRepuesto = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRepuestos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(650, 540));
        setPreferredSize(new java.awt.Dimension(650, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("00001");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 120, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Servicio");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 430, 30));

        btnSeleccionarServicio.setText("SELECCIONAR");
        btnSeleccionarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarServicioActionPerformed(evt);
            }
        });
        add(btnSeleccionarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 120, 30));

        btnSeleccionarRepuesto.setText("SELECCIONAR");
        btnSeleccionarRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarRepuestoActionPerformed(evt);
            }
        });
        add(btnSeleccionarRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 120, 30));

        jButton3.setText("PROCESAR");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 120, 50));

        tableRepuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Descripcion", "Precio", "Cantidad", "Total"
            }
        ));
        jScrollPane1.setViewportView(tableRepuestos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 570, 120));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Descripcion", "Precio"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 570, 130));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Repuesto");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("BOLETA ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 210, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarRepuestoActionPerformed

  DialogBuscarRepuesto repuesto = new DialogBuscarRepuesto((JFrame) SwingUtilities.getWindowAncestor(this), true);
    repuesto.setVisible(true);
    
    
    }//GEN-LAST:event_btnSeleccionarRepuestoActionPerformed

    private void btnSeleccionarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarServicioActionPerformed
      DialogBuscarServicio servicio = new DialogBuscarServicio((JFrame) SwingUtilities.getWindowAncestor(this), true);
       servicio.setVisible(true);// TODO add your handling code here: 
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarServicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionarRepuesto;
    private javax.swing.JButton btnSeleccionarServicio;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tableRepuestos;
    // End of variables declaration//GEN-END:variables
}
