/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyecto.alquilerpelas.paneles;

/**
 *
 * @author santo
 */
public class fcarterlera extends javax.swing.JFrame {

    /**
     * Creates new form fcarterlera
     */
    public fcarterlera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnsusi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnsusi.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEX PUA\\Desktop\\netbeans\\AlquilerPelas\\AlquilerPelas\\src\\main\\java\\com\\proyecto\\alquilerpelas\\paneles\\susi.jpg")); // NOI18N
        btnsusi.setText("jButton1");
        btnsusi.setPreferredSize(new java.awt.Dimension(500, 600));
        btnsusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsusiActionPerformed(evt);
            }
        });

        jLabel3.setText("Destacada:");

        jLabel4.setText("Sinopsis");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsusi, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnsusi, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fnaf.jpg"))); // NOI18N
        jButton2.setText("jButton1");
        jButton2.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel5.add(jButton2);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyecto/alquilerpelas/paneles/interstellar.jpg"))); // NOI18N
        jButton5.setText("jButton1");
        jButton5.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel5.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyecto/alquilerpelas/paneles/df.jpg"))); // NOI18N
        jButton6.setText("jButton1");
        jButton6.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel5.add(jButton6);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEX PUA\\Desktop\\netbeans\\AlquilerPelas\\AlquilerPelas\\src\\main\\java\\img\\unnamed.jpg")); // NOI18N
        jButton3.setText("jButton1");
        jButton3.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel5.add(jButton3);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/proyecto/alquilerpelas/paneles/avengers.jpg"))); // NOI18N
        jButton7.setText("jButton1");
        jButton7.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel5.add(jButton7);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEX PUA\\Desktop\\netbeans\\AlquilerPelas\\AlquilerPelas\\src\\main\\java\\img\\ironman.jpg")); // NOI18N
        jButton4.setText("jButton1");
        jButton4.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel5.add(jButton4);

        jPanel6.setPreferredSize(new java.awt.Dimension(120, 169));

        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEX PUA\\Desktop\\netbeans\\AlquilerPelas\\AlquilerPelas\\src\\main\\java\\img\\monster.jpg")); // NOI18N
        jButton8.setText("jButton1");
        jButton8.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel6.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEX PUA\\Desktop\\netbeans\\AlquilerPelas\\AlquilerPelas\\src\\main\\java\\img\\ted.jpg")); // NOI18N
        jButton9.setText("jButton1");
        jButton9.setPreferredSize(new java.awt.Dimension(120, 169));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9);

        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEX PUA\\Desktop\\netbeans\\AlquilerPelas\\AlquilerPelas\\src\\main\\java\\img\\pedito.jpg")); // NOI18N
        jButton10.setText("jButton1");
        jButton10.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel6.add(jButton10);

        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEX PUA\\Desktop\\netbeans\\AlquilerPelas\\AlquilerPelas\\src\\main\\java\\img\\lorax.jpg")); // NOI18N
        jButton11.setText("jButton1");
        jButton11.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel6.add(jButton11);

        jButton12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEX PUA\\Desktop\\netbeans\\AlquilerPelas\\AlquilerPelas\\src\\main\\java\\img\\tengoFE.jpg")); // NOI18N
        jButton12.setText("jButton1");
        jButton12.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel6.add(jButton12);

        jButton13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEX PUA\\Desktop\\netbeans\\AlquilerPelas\\AlquilerPelas\\src\\main\\java\\img\\deadpool.jpg")); // NOI18N
        jButton13.setText("jButton1");
        jButton13.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel6.add(jButton13);

        jButton14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEX PUA\\Desktop\\netbeans\\AlquilerPelas\\AlquilerPelas\\src\\main\\java\\img\\spirit.jpg")); // NOI18N
        jButton14.setText("jButton1");
        jButton14.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel7.add(jButton14);

        jButton15.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEX PUA\\Desktop\\netbeans\\AlquilerPelas\\AlquilerPelas\\src\\main\\java\\img\\proyectoX.jpg")); // NOI18N
        jButton15.setText("jButton1");
        jButton15.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel7.add(jButton15);

        jButton16.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEX PUA\\Desktop\\netbeans\\AlquilerPelas\\AlquilerPelas\\src\\main\\java\\img\\enigma.jpg")); // NOI18N
        jButton16.setText("jButton1");
        jButton16.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel7.add(jButton16);

        jButton17.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEX PUA\\Desktop\\netbeans\\AlquilerPelas\\AlquilerPelas\\src\\main\\java\\img\\batman.jpg")); // NOI18N
        jButton17.setText("jButton1");
        jButton17.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel7.add(jButton17);

        jButton18.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEX PUA\\Desktop\\netbeans\\AlquilerPelas\\AlquilerPelas\\src\\main\\java\\img\\midiosLOKI.jpg")); // NOI18N
        jButton18.setText("jButton1");
        jButton18.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel7.add(jButton18);

        jButton19.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALEX PUA\\Desktop\\netbeans\\AlquilerPelas\\AlquilerPelas\\src\\main\\java\\img\\ultimosoldado.jpg")); // NOI18N
        jButton19.setText("jButton1");
        jButton19.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel7.add(jButton19);

        jButton20.setText("jButton1");
        jButton20.setPreferredSize(new java.awt.Dimension(120, 169));
        jPanel7.add(jButton20);

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(472, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jMenu1.setText("Peliculas");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Series");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1428, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsusiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsusiActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fcarterlera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fcarterlera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fcarterlera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fcarterlera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fcarterlera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsusi;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
